[env:esp32dev]
platform = espressif32
;board = esp32dev
framework = arduino
board_build.partitions = huge_app.csv
lib_deps =
    adafruit/RTClib@^2.1.4
    bblanchon/ArduinoJson@^6.21.5
    SPI
    Wire

;upload_port =  /dev/cu.usbserial-0001
;monitor_port = /dev/cu.usbserial-0001
lib_ldf_mode = chain+
;build_flags=
;    -D SOC_WIFI_SUPPORTED=1
;    -Isrc
;    -I${platformio.packages_dir}/framework-arduinoespressif32/libraries/SPI/src

# Last 2 are for code cell
upload_port =  /dev/cu.usbmodem101
monitor_port = /dev/cu.usbmodem101
board = esp32-c3-devkitm-1
board_build.mcu = esp32c3
board_build.f_cpu = 160000000L
build_flags=
    -D SOC_WIFI_SUPPORTED=1
    -Isrc
    -I${platformio.packages_dir}/framework-arduinoespressif32/libraries/SPI/src
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
