python gen.py "lovely" \
  --width-mm 50 \
  --height-mm 50 \
  --one-line \
  --font "Pacifico" \
  --raster-mm 0.02 \
  --close-mm 0 \
  --mask-method render \
  --skeleton-method thin \
  --thin-max-iter 300 \
  --smooth-chaikin 0 --rdp-eps-mm 0 \
  --optimize-lr --lr-penalty 35 \
  --stitch-mm 2.0 --bridge-mm 0 \
  --poly-step-mm 0.15 \
  --min-stroke-mm 0.001 \
  --debug-views \
  --simulate \
  --force-lr